[general]
destination = "$HOME/.config/hypr/lua/monitors.lua"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_ADP0"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_ADP0"

[profiles.laptop-only]
config_file = "/home/tuasananh/.config/hyprdynamicmonitors/hyprconfigs/laptop-only.go.tmpl"
config_file_type = "template"
[profiles.laptop-only.conditions]

[[profiles.laptop-only.conditions.required_monitors]]
description = "BOE 0x0B8B 0x00000001"
monitor_tag = "laptop"
