term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: 1e1e2e
term_foreground: cdd6f4
term_background_bright: 585b70
term_foreground_bright: cdd6f4

interface_branding:


timeout: 5

/Arch Linux
    protocol: efi
    path: boot():/EFI/Linux/arch-linux.efi
    cmdline: cryptdevice=PARTUUID=44cd382a-4e63-4ea9-9d1c-1baa33ad68c1:root root=/dev/mapper/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs

/Windows 11
    protocol: efi 
    path: guid(9ada632f-d232-4389-824d-232ee029190a):/EFI/Microsoft/Boot/bootmgfw.efi


